Quickstart Example
------------------

Interested in creating a fully functional static website using **sdep**,
`travis-ci <https://travis-ci.org/>`_ and `Cloudflare
<https://www.cloudflare.com/>`_? Read on!

.. toctree::
   :maxdepth: 2

   example

User's Guide
------------

This aspect of the documentation gives guidance with respect to getting started
with **sdep**.

.. toctree::
   :maxdepth: 2

   cli

API Reference
-------------

Information on specific functions, classes, and methods.

.. toctree::
   :maxdepth: 2

   api
